# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-20 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_auto_20200819_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='abbreviation',
        ),
        migrations.AddField(
            model_name='mapobj',
            name='abbreviation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
