# Generated by Django 3.1.1 on 2020-09-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_auto_20200820_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='sketchup',
            field=models.CharField(help_text='E.g., https://3dwarehouse.sketchup.com/model.html?id=<code>54b7f313bf315a3a85622796b26c9e66</code>', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mapobj',
            name='googlemap_point',
            field=models.CharField(help_text='E.g., <code>[28.6017, -81.2005]</code>', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mapobj',
            name='id',
            field=models.CharField(help_text='<strong class="caution">Caution</strong>: changing may break external resources (used for links and images)', max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mapobj',
            name='image',
            field=models.ImageField(upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='sketchup',
            field=models.CharField(help_text='E.g., https://3dwarehouse.sketchup.com/model.html?id=<code>54b7f313bf315a3a85622796b26c9e66</code>', max_length=50, null=True),
        ),
    ]
